l_spanish:
 # Societal value: Taxis vs Dynatoi
 cc_taxis_focus: "Táxis"
 cc_dynatoi_focus: "Dynatoí"
 cc_taxis_vs_cc_dynatoi: "$cc_taxis_focus$ frente a $cc_dynatoi_focus$"
 cc_taxis_vs_cc_dynatoi_desc: "Un [country|e] ordenado por $cc_taxis_focus$ gobierna a través del fisco y las oficinas imperiales: funcionarios asalariados, impuestos tasados y una corte que nombra y destituye a voluntad. Uno moldeado por $cc_dynatoi_focus$ gobierna a través de sus familias provinciales, que poseen la tierra, reclutan a los soldados y esperan que se consulte a los [ShowPopTypeName('nobles')] en lugar de que se les den instrucciones."

 # Drift modifier types
 MODIFIER_TYPE_NAME_monthly_towards_cc_taxis: "Progreso mensual hacia los Táxis"
 MODIFIER_TYPE_DESC_monthly_towards_cc_taxis: "Esto afecta al cambio hacia los [societal_values|e] de [ShowSocietyDirectionName('cc_taxis')]."
 MODIFIER_TYPE_NAME_monthly_towards_cc_dynatoi: "Progreso mensual hacia los Dynatoí"
 MODIFIER_TYPE_DESC_monthly_towards_cc_dynatoi: "Esto afecta al cambio hacia los [societal_values|e] de [ShowSocietyDirectionName('cc_dynatoi')]."

 # Static modifiers
 STATIC_MODIFIER_NAME_cc_taxis_progress_cabinet_efficiency: "Enfoque del Gabinete"
 STATIC_MODIFIER_NAME_cc_dynatoi_progress_cabinet_efficiency: "Enfoque del Gabinete"
