l_german:
 # Societal value: Taxis vs Dynatoi
 cc_taxis_focus: "Táxis"
 cc_dynatoi_focus: "Dynatoí"
 cc_taxis_vs_cc_dynatoi: "$cc_taxis_focus$ vs. $cc_dynatoi_focus$"
 cc_taxis_vs_cc_dynatoi_desc: "Ein [country|e], das nach $cc_taxis_focus$ geordnet ist, regiert über den Fiskus und die kaiserlichen Büros: besoldete Beamte, festgesetzte Steuern und einen Hof, der nach Belieben ernennt und entlässt. Eines, das durch $cc_dynatoi_focus$ geprägt ist, regiert über seine Provinzfamilien, welche das Land besitzen, die Soldaten aufstellen und erwarten, dass die [ShowPopTypeName('nobles')] konsultiert statt angewiesen werden."

 # Drift modifier types
 MODIFIER_TYPE_NAME_monthly_towards_cc_taxis: "Monatlicher Fortschritt zu den Táxis"
 MODIFIER_TYPE_DESC_monthly_towards_cc_taxis: "Dies beeinflusst die Veränderung hin zu den [societal_values|e] der [ShowSocietyDirectionName('cc_taxis')]."
 MODIFIER_TYPE_NAME_monthly_towards_cc_dynatoi: "Monatlicher Fortschritt zu Dynatoí"
 MODIFIER_TYPE_DESC_monthly_towards_cc_dynatoi: "Dies beeinflusst die Veränderung hin zu den [societal_values|e] der [ShowSocietyDirectionName('cc_dynatoi')]."

 # Static modifiers
 STATIC_MODIFIER_NAME_cc_taxis_progress_cabinet_efficiency: "Kabinettsschwerpunkt"
 STATIC_MODIFIER_NAME_cc_dynatoi_progress_cabinet_efficiency: "Kabinettsschwerpunkt"
